-- ============================================================================
-- Security Hardening Migration (003)
--
-- This migration adds:
--   1. Hardened get_user_stats with ownership verification
--   2. Server-side rate limiting via PostgreSQL functions
--   3. CHECK constraints on input lengths (defense in depth)
--   4. Duplicate question detection trigger
--
-- Run this in the Supabase SQL Editor.
-- ============================================================================

-- ============================================================================
-- 1. Hardened get_user_stats — add ownership verification
-- ============================================================================

-- Drop existing function to replace with hardened version
DROP FUNCTION IF EXISTS public.get_user_stats(uuid);

-- New version with explicit ownership check via auth.uid()
CREATE OR REPLACE FUNCTION public.get_user_stats(p_uid uuid)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
AS $$
  DECLARE
    is_owner BOOLEAN;
    is_moderator BOOLEAN;
    result json;
  BEGIN
    -- Check if the authenticated user owns this profile
    SELECT (auth.uid() = p_uid) INTO is_owner;
    
    -- Check if the authenticated user is a moderator
    SELECT EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid() AND users.role = 'moderator'
    ) INTO is_moderator;
    
    -- Only allow if owner or moderator
    IF NOT is_owner AND NOT is_moderator THEN
      RAISE EXCEPTION 'Access denied: You can only view your own stats';
    END IF;
    
    -- Return stats
    SELECT json_build_object(
      'question_count', (SELECT count(*) FROM public.questions WHERE author_uid = p_uid),
      'answer_count',   (SELECT count(*) FROM public.answers   WHERE author_uid = p_uid),
      'bookmark_count', (SELECT count(*) FROM public.bookmarks WHERE user_id   = p_uid)
    ) INTO result;
    
    RETURN result;
  END;
$$;

-- ============================================================================
-- 2. Server-side rate limiting functions
-- ============================================================================

-- Create a table to track rate limit violations (for server-side enforcement)
CREATE TABLE IF NOT EXISTS public.rate_limit_violations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id),
  action_name text NOT NULL,
  violation_count int DEFAULT 1,
  first_violation_at timestamptz DEFAULT now(),
  last_violation_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  UNIQUE (user_id, action_name)
);

-- Enable RLS on rate_limit_violations
ALTER TABLE public.rate_limit_violations ENABLE ROW LEVEL SECURITY;

-- Users can only see their own violations
DROP POLICY IF EXISTS "Users can view own rate limit violations" ON public.rate_limit_violations;
CREATE POLICY "Users can view own rate limit violations"
  ON public.rate_limit_violations FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- Users can only insert their own violations
DROP POLICY IF EXISTS "Users can insert own rate limit violations" ON public.rate_limit_violations;
CREATE POLICY "Users can insert own rate limit violations"
  ON public.rate_limit_violations FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- Function to check and record rate limit violations
CREATE OR REPLACE FUNCTION public.check_rate_limit(
  p_action_name text,
  p_max_attempts int DEFAULT 10,
  p_window_minutes int DEFAULT 60
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
  DECLARE
    current_user_id uuid := auth.uid();
    violation_count int;
    is_allowed boolean;
  BEGIN
    IF current_user_id IS NULL THEN
      -- No authenticated user — allow but log (could implement IP-based limiting)
      RETURN true;
    END IF;
    
    -- Count violations in the time window
    SELECT COALESCE(sum(violation_count), 0)
    INTO violation_count
    FROM public.rate_limit_violations
    WHERE user_id = current_user_id
      AND action_name = p_action_name
      AND last_violation_at > now() - (p_window_minutes || ' minutes')::interval;
    
    IF violation_count >= p_max_attempts THEN
      RETURN false;
    END IF;
    
    RETURN true;
  END;
$$;

-- Function to record a rate limit violation (call after rejected action)
CREATE OR REPLACE FUNCTION public.record_rate_limit_violation(p_action_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
  DECLARE
    current_user_id uuid := auth.uid();
  BEGIN
    IF current_user_id IS NULL THEN
      RETURN;
    END IF;
    
    -- Insert or update violation record
    INSERT INTO public.rate_limit_violations (user_id, action_name)
    VALUES (current_user_id, p_action_name)
    ON CONFLICT (user_id, action_name) DO UPDATE
      SET violation_count = rate_limit_violations.violation_count + 1,
          last_violation_at = now();
  END;
$$;

-- ============================================================================
-- 3. CHECK constraints on input lengths (defense in depth)
-- ============================================================================

-- Add length constraints to questions table
ALTER TABLE public.questions DROP CONSTRAINT IF EXISTS questions_body_length;
ALTER TABLE public.questions DROP CONSTRAINT IF EXISTS questions_tag_length;
ALTER TABLE public.questions DROP CONSTRAINT IF EXISTS questions_author_tag_length;
ALTER TABLE public.questions
  ADD CONSTRAINT questions_body_length CHECK (char_length(body) <= 5000),
  ADD CONSTRAINT questions_tag_length CHECK (char_length(tag) <= 50),
  ADD CONSTRAINT questions_author_tag_length CHECK (char_length(author_tag) <= 100);

-- Add length constraints to answers table
ALTER TABLE public.answers DROP CONSTRAINT IF EXISTS answers_body_length;
ALTER TABLE public.answers DROP CONSTRAINT IF EXISTS answers_author_tag_length;
ALTER TABLE public.answers
  ADD CONSTRAINT answers_body_length CHECK (char_length(body) <= 5000),
  ADD CONSTRAINT answers_author_tag_length CHECK (char_length(author_tag) <= 100);

-- Add length constraints to users table
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_display_tag_length;
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_branch_length;
ALTER TABLE public.users
  ADD CONSTRAINT users_display_tag_length CHECK (char_length(display_tag) <= 100),
  ADD CONSTRAINT users_branch_length CHECK (char_length(branch) <= 50);

-- Add length constraints to wiki_articles table
ALTER TABLE public.wiki_articles DROP CONSTRAINT IF EXISTS wiki_articles_title_length;
ALTER TABLE public.wiki_articles DROP CONSTRAINT IF EXISTS wiki_articles_summary_length;
ALTER TABLE public.wiki_articles DROP CONSTRAINT IF EXISTS wiki_articles_category_length;
ALTER TABLE public.wiki_articles
  ADD CONSTRAINT wiki_articles_title_length CHECK (char_length(title) <= 200),
  ADD CONSTRAINT wiki_articles_summary_length CHECK (char_length(summary) <= 500),
  ADD CONSTRAINT wiki_articles_category_length CHECK (char_length(category) <= 50);

-- ============================================================================
-- 4. Duplicate question detection trigger
-- ============================================================================

-- Required for levenshtein() function used in duplicate detection
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;

-- Function to detect potential duplicate questions
CREATE OR REPLACE FUNCTION public.check_duplicate_question()
RETURNS TRIGGER AS $$
  DECLARE
    similar_count int;
    similar_question_id uuid;
  BEGIN
    -- Check for very similar questions (same body or >90% similar)
    -- Only check for recent questions (last 24 hours) to avoid performance issues
    SELECT COUNT(*) INTO similar_count
    FROM public.questions
    WHERE created_at > now() - interval '24 hours'
      AND author_uid = NEW.author_uid
      AND id != NEW.id  -- Exclude the current row being inserted
      AND (
        body = NEW.body  -- Exact match
        OR (
          -- Levenshtein-like check: very similar (simple character overlap)
          -- This is a simplified check; production might use pg_trgm extension
          length(NEW.body) > 10
          AND levenshtein(lower(NEW.body), lower(body)) < 5
        )
      );

    -- If similar question exists, allow but flag (could extend to reject)
    -- For now, we just log — extend this to raise exception if stricter policy needed
    IF similar_count > 0 THEN
      RAISE NOTICE 'Similar question detected (ID: %). Consider reviewing for duplicates.', similar_question_id;
    END IF;
    
    RETURN NEW;
  END;
$$ LANGUAGE plpgsql;

-- Create the trigger
DROP TRIGGER IF EXISTS duplicate_question_check ON public.questions;
CREATE TRIGGER duplicate_question_check
  BEFORE INSERT ON public.questions
  FOR EACH ROW
  EXECUTE FUNCTION public.check_duplicate_question();

-- ============================================================================
-- 5. Additional security: Restrict auth.users table access
-- ============================================================================

-- The auth.users table is already restricted by Supabase, but let's ensure
-- our RLS policies don't inadvertently expose it

-- Ensure RLS is enabled on auth.users (managed by Supabase, but verify)
-- Note: You cannot directly alter auth schema tables, but we can ensure
-- our own tables don't accidentally expose auth data

-- ============================================================================
-- 6. Indexes for performance with new constraints
-- ============================================================================

-- Index for rate limit violation queries
CREATE INDEX IF NOT EXISTS idx_rate_limit_violations_user_action
  ON public.rate_limit_violations (user_id, action_name, last_violation_at);

-- Index for recent questions (without time-bound predicate to avoid IMMUTABLE requirement)
CREATE INDEX IF NOT EXISTS idx_questions_author_created
  ON public.questions (author_uid, created_at DESC);

-- Index for questions tag queries (common filter)
CREATE INDEX IF NOT EXISTS idx_questions_tag_created
  ON public.questions (tag, created_at DESC);

-- Index for wiki articles category queries
CREATE INDEX IF NOT EXISTS idx_wiki_articles_category_status
  ON public.wiki_articles (category, status);

-- ============================================================================
-- Summary
-- ============================================================================
--
-- This migration adds:
--   ✓ Hardened get_user_stats with ownership verification
--   ✓ Server-side rate limiting infrastructure
--   ✓ Database-level CHECK constraints on input lengths  
--   ✓ Duplicate question detection
--   ✓ Performance indexes
--
-- Run in Supabase SQL Editor to apply.
-- ============================================================================